apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: kafka-slurp
build:
  tagPolicy:
    gitCommit:
      prefix: "skaffold-"
  artifacts:
  - image: kafka-slurp
    context: .
    jib: {}
deploy:
  kubectl:
    manifests: ["k8s/*.yaml"]
